### ISSUE TITLE
[Minor Nitpick] Only allow right-click output on an empty hand

### ISSUE THREAD

**Issue by Jvs34** [Seraphaestus/FactoriOres#1]
Most of Create's containers only allow the player to retrieve the output on an empty hand, such as belts, millstones, depots and etc.

I know this mod has more than just the Mechanical Miner but I thought that getting stuff out while trying to stack miners together felt odd compared to the usual Create behaviour.

**Comment by Seraphaestus** [comment]
Thanks for the feedback!
I don't think this is an issue as you aren't really supposed to stack miners right next to eachother (their legs clip, and the default configs give the survival variants at least a 3x3 range, after all). Also, your problem may be that you're trying to place miners by right-clicking the face of another miner, when they currently have to be placed by right-clicking the top face of an ore deposit block. So I have now:
1. made it so you can't place miners in the 3x3 area around an existing miner. You can disable this in the configs though!
2. changed the miner empty-hand output behaviour to match Create's millstone; this actually means you can still take out items with a full hand, but it doesn't play the hand animation, which is how the millstone seems to work. Hopefully this will feel more natural!

**Comment by Jvs34** [comment]
Sounds good. 👍
